services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlite
    environment:
      APP_PORT: 8050
      DB_HOST: sqlite
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8050

  sqlite:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./data:/database
    ports:
      - 5432:5432
    command: ["tail", "-f", "/dev/null"]

volumes:
  data: